// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwyxgrraqasivphiarnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3eXhncnJhcWFzaXZwaGlhcm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDYwMDUsImV4cCI6MjA1OTM4MjAwNX0.ghOY5QaGk57bqML0WkHUaGsY-J7dqCx4kjm_VES8JZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);